version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://postgres/postgres -schemas=public -user=postgres -password=postgres -connectRetries=5 migrate
    volumes:
      - ./src/main/resources:/flyway/sql
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8080"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"

  clamav:
    #debian: image: mkodockx/docker-clamav
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clam:/var/lib/clamav

  wso2am:
    image: wso2/wso2am
    container_name: wso2
    ports:
      - "8243:8243"
      - "8280:8280"
      - "9443:9443"
    volumes:
      - wso2:/var/lib/wso2

  web:
    build: .
    container_name: web
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    command: java -jar partners-bootcamp-1.0-SNAPSHOT.jar
    depends_on:
      - postgres
      - flyway
      - rabbitmq
      - clamav
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
    - web:/home/app

volumes:
  pgdata:
    driver: local
  clam:
  wso2:
  web:
