
### Basic Hello World POST request
GET http://localhost:8080/rest/bootcamp/hello
Content-Type: application/json

### Basic Hello World POST request
POST http://localhost:8080/rest/bootcamp/hello/person
Content-Type: application/json

{
  "name": "Jaroslav",
  "surname": "Svoboda"
}

### Basic Hello World GET request
GET http://localhost:8080/rest/bootcamp/hello/person
Content-Type: application/json


### Task File Upload request
POST http://localhost:8080/rest/bootcamp/upload-file
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="sample.pdf"

< ./src/test/resources/sample.pdf



### Task Get Uploaded File status request
GET http://localhost:8080/rest/bootcamp/upload-file/1/status
Content-Type: application/json

### Task Get Uploaded File status request
GET http://localhost:8080/rest/bootcamp/upload-file/2/status
Content-Type: application/json

### Task Get Uploaded File status request
GET http://localhost:8080/rest/bootcamp/upload-file/3/status
Content-Type: application/json

### Task Get Uploaded File status request
GET http://localhost:8080/rest/bootcamp/upload-file/4/status
Content-Type: application/json

### Task Get Uploaded File status request
GET http://localhost:8080/rest/bootcamp/upload-file/5/status
Content-Type: application/json

### Test call Choreo
GET https://5a593a8e-3383-4a99-810c-6b4c366213bd-dev.e1-eu-north-azure.choreoapis.dev/xgzf/partnersbootcamp/product-catalog-5c6/1.0.0/rest/bootcamp/hello
Content-Type: application/json
